### ISSUE TITLE
팀 과제 일정 문의.

### ISSUE THREAD

**Issue by Akows** [preonboarding-internship/qna-12th#1]
안녕하세요, 2/3주차 팀 과제 일정과 관련하여 문의할 것이 있어 글을 작성합니다.

이번 1주차 과제 일정이 화요일 세션이 끝난 이후 금요일 자정까지 Git Repo 링크를 업로드하는 것인데,

2/3주차 과제도 동일한 일정으로 진행되는지 문의합니다.

**Comment by walking-sunset** [comment]
안녕하세요, 2 / 3주차 팀 과제 일정도 동일하게 화요일 수업 종료 후 ~ 금요일 자정까지로 진행될 예정입니다.

https://www.notion.so/4-d3c5214bddcc49c282a87c32a444a49a?pvs=4#83f692be347747c6b7a6eed1b6011866

전체 과제 일정은 위 페이지에서 확인하실 수 있습니다 :)
