### ISSUE TITLE
과제에 format, lint, git hook 라이브러리 적용 여부

### ISSUE THREAD

**Issue by bangcr** [preonboarding-internship/qna-12th#3]
안녕하세요 멘토님, 늘 최고의 강의와 아낌없는 지원을 해주심에 감사의 말씀을 먼저 드립니다.  
과제를 진행함에 있어 dependency관련 문의사항이 있어 질문 드립니다.

2주차 과제를 진행함에 있어서 1주차 강의에서 배운 eslint, prettier, husky를 적용해보고자, 설치를 진행하다가 '기재된 라이브러리 외 사용 불가'라는 문구가 떠올라 설치를 중단했습니다. 이러한 라이브러리 또한 사용이 불가능하다고 생각하면 될까요?

**Comment by yeonuk-hwang** [comment]
안녕하세요, 충림님 라이브러리 사용 제한은 기능에 영향을 미치는 라이브러리를 대상으로 적용됩니다. 따라서 세팅에 필요한 라이브러리들(craco, eslint, husky, prettier)처럼 개발환경에서만 사용되고 실제 코드의 기능의 영향을 미치지 않는 경우 사용하실 수 있습니다 :)

**Comment by bangcr** [comment]
답변해주셔서 감사합니다. 궁금증이 해결되었습니다.
