### ISSUE TITLE
협동 과제 진행 방법에 대한 문의.

### ISSUE THREAD

**Issue by Akows** [preonboarding-internship/qna-12th#5]
안녕하십니까. 

협동 과제 진행 방법에 질문이 있어 글을 작성합니다.

현재 저희 팀은 기능 구현에 앞서서, 우선 과제의 주요 기능들을 분석하고 팀 회의를 통해 이 기능의 구현 방식은 어떤 것들이 있을지 논의한 다음. 어떤 방법이 가장 적합한 것인지 선정하고 그에 맞춰 각자 기능을 구현하고 있습니다.

그런데 그 다음 순서인 제출용 최종 결과물을 제작하는 방법에 대해서,

전체 회의를 통해 서로 구현한 결과물 중에서 가장 잘 만들었다고 생각되는 것 하나를 선출한 다음, 논의를 거쳐 개선점이나 수정 사항 등을 반영하여 최종 결과물로 제출해도 괜찮은 것인지 질문합니다.

**Comment by Akows** [comment]
또한 위 방식으로 과제를 진행했을 때, 팀 Repo의 커밋 기록에 모든 팀원들의 흔적을 남겨야하는지도 질문합니다.

개선점이나 수정 사항 논의는 함께하는데, 이걸 코드에 적용할 때는 한 사람이 전담해도 되는지 아니면 모두 나누어야 하는지 정해진 규칙이 있는지요.

**Comment by yeonuk-hwang** [comment]
> 현재 저희 팀은 기능 구현에 앞서서, 우선 과제의 주요 기능들을 분석하고 팀 회의를 통해 이 기능의 구현 방식은 어떤 것들이 있을지 논의한 다음. 어떤 방법이 가장 적합한 것인지 선정하고 그에 맞춰 각자 기능을 구현하고 있습니다.

> 그런데 그 다음 순서인 제출용 최종 결과물을 제작하는 방법에 대해서,

> 전체 회의를 통해 서로 구현한 결과물 중에서 가장 잘 만들었다고 생각되는 것 하나를 선출한 다음, 논의를 거쳐 개선점이나 수정 사항 등을 반영하여 최종 결과물로 제출해도 괜찮은 것인지 질문합니다.

- 네 해당방식으로 진행하셔도 되며, 단순히 선출하고 끝이 아닌 거기서 개선점, 수정 사항을 반영해서 최종 결과물로 만드는 것이 동료학습 잘 진행하고 계신 것 같습니다~!

> 또한 위 방식으로 과제를 진행했을 때, 팀 Repo의 커밋 기록에 모든 팀원들의 흔적을 남겨야하는지도 질문합니다.

- 명시적으로 모든 팀원의 흔적은 남길필요가 없습니다, 단지 원래 커밋 메세지의 목적에 맞게 코드가 어떤 목적으로 작성되었는지, 변경사항 요약 등만 있으면 됩니다.

> 개선점이나 수정 사항 논의는 함께하는데, 이걸 코드에 적용할 때는 한 사람이 전담해도 되는지 아니면 모두 나누어야 하는지 정해진 규칙이 있는지요.

- 코드에 적용 하는 것에 대한 제약사항은 없습니다. 팀 안에서 좋은 효과를 낼 수 있다고 생각되는 방법으로 진행하시면 됩니다.

궁금한 사항이 해결되었기를 바랍니다 :)

**Comment by Akows** [comment]
'단지 원래 커밋 메세지의 목적에 맞게 코드가 어떤 목적으로 작성되었는지, 변경사항 요약 등만 있으면 됩니다.'

이 부분은 팀 Repo의 Readme 파일에 작성하면 괜찮을까요?

**Comment by yeonuk-hwang** [comment]
> '단지 원래 커밋 메세지의 목적에 맞게 코드가 어떤 목적으로 작성되었는지, 변경사항 요약 등만 있으면 됩니다.'
이 부분은 팀 Repo의 Readme 파일에 작성하면 괜찮을까요?

네 그렇게 진행해주세요 :)
