### ISSUE TITLE
안녕하세요 과제 라이브러리 사용 관련 문의드립니다.

### ISSUE THREAD

**Issue by taegeun1111** [preonboarding-internship/qna-12th#6]
로딩바를 구현하는 과정에서 로딩 spinner의 라이브러리인 react-loader-spinner를 사용해도 괜찮을까요?
<img width="150" alt="Screen Shot 2023-09-01 at 10 59 52 AM" src="https://github.com/walking-sunset/qna-12th/assets/122959190/974ce2e8-5473-4041-8172-ad0783965a6a">

**Comment by yeonuk-hwang** [comment]
네, UI적인 기능만 수행하기에 UI 라이브러리로 판단 사용하셔도 됩니다. 추가적으로 라이브러리 사용 여부에 대해 질문하실 땐 해당 라이브러리의 이름, 설명, 그리고 공식문서 링크를 함께 첨부해주시는게 좋습니다.
