### ISSUE TITLE
3주차 배포 관련 질문

### ISSUE THREAD

**Issue by devseop** [preonboarding-internship/qna-12th#9]
안녕하세요, 12차 수강생 여러분. 이번 3주차 과제 진행 간에 있어 궁금한 점이 있어 이슈를 남깁니다.

이번 과제는 기존에 있던 API가 아닌 멘토님의 레포에 있는 db.json을 이용하여 구현하는 방식이었는데, 
해당 과제 배포시에는 백엔드를 어떻게 처리할 것인지 혹은 예정인지 궁금합니다.

현재 저희 2팀은 https://my-json-server.typicode.com/ 를 이용해 페이크 서버를 만드는 방법을 논의 중입니다.
다만 해당 사이트에서는 캐시 문제가 있어 이용에 어려움이 있는데요.

그래서 다른 팀에서는 어떻게 진행할 예정인지 팁을 얻고자 질문을 남깁니다.

다양한 의견이 공유되면 좋겠습니다.

감사합니다!

**Comment by Woogie-94** [comment]
https://github.com/kitloong/json-server-vercel 

강사님이 공유해주신 repo를 기반으로 위의 링크를 참고해 vercel에 배포하면 간단한 json-server가 만들어집니다.

**Comment by Akows** [comment]
저희는 Vercel의 서버리스 함수를 이용해서 json-server의 기능을 모방하여 DB/백엔드 코드를 작성해서 Vercel에서 배포하였습니다.

**Comment by NR0617** [comment]
https://github.com/jesperorb/json-server-heroku 를 참조하고 glitch로 배포했습니다 위에 있는 vercel이랑 거의 비슷하네요
